### ISSUE TITLE
Dependencies of dependencies that reference directories are not resolved to versions

### ISSUE THREAD

**Issue by markwaddle** [gerbenoostra/poetry-plugin-mono-repo-deps#11]
Example:
lib-a depends on lib-b by directory path
lib-b depends on lib-c by directory path

when running `poetry export` for `lib-a`, the lock "info" for `lib-b` looks like the following after `modify_locked_package_to_named` has altered it:
```
{
  "name": "lib-b",
  "version": "0.1.0",
  "description": "lib B",
  "optional": false,
  "files": [],
  "dependencies": {
    "lib-c": {
      "path": "../lib-c",
      "develop": true
    }
  }
}
```

in the case of `poetry export`, it then fails with an error

**Comment by gerbenoostra** [comment]
Hi @markwaddle , thanks for reporting and providing an initial fix.

I've modified the fix to resolve the specific version, instead of using the * wildcard, and verified it with a transitive path & git dependency.

I've released it in v0.2.3, let me know if you still run into issues.
