### ISSUE TITLE
Poetry command fails to run from folders without a pyproject.toml (inc poetry init and poetry --version)

### ISSUE THREAD

**Issue by PSC-MM** [gerbenoostra/poetry-plugin-mono-repo-deps#5]
Hello,

Very much appreciating this plugin, although we have found an issue with it.

With the plugin installed, the following commands fail, if run from a folder without a pyproject.toml file:

poetry --version
poetry init
poetry self show plugins

The error message in all cases is:

Poetry could not find a pyproject.toml file in [current folder] or its parents.

If I uninstall the plugin, they succeed.

I've tried installing (and then uninstalling) the plugin via:
 - pip install in the poetry virtual environment (%APPDATA%\pypoetry\venv\Scripts)
 - poetry self add poetry-plugin-mono-repo-deps (which works in a folder with a pyproject.toml file)

Just for comparison and triage I tried installing another plugin and didn't get this behaviour, while colleagues are seeing the same behaviour with this plugin on their machines.

We're on Windows machines and have installed Poetry via PowerShell using the official installer.

**Comment by gerbenoostra** [comment]
Hi @PSC-MM , thanks for reporting and sorry for the late response. I've fixed it in the above MR and released it in v0.2.1.

**Comment by PSC-MM** [comment]
Hi @gerbenoostra and thank you very much. Installed v0.2.1 and given it a few runs, looks good to me too. Much appreciated.
