### ISSUE TITLE
Plugin is not active

### ISSUE THREAD

**Issue by soufea** [gerbenoostra/poetry-plugin-mono-repo-deps#7]
Hello,

Thanks for the reply and great to hear you are planning to maintain this further !

I am moving the discussion here from this [issue](https://github.com/python-poetry/poetry/issues/2270#issuecomment-2091745168).

Here is a minimal example to reproduce. Basically, doing an export or build in folder B doesn't change anything, no errors.

Structure
```
── pyproject.toml
└── repo
    ├── A
    │   └── pyproject.toml
    └── B
        ├── poetry.lock
        ├── pyproject.toml
        └── reqs.txt
```

*root pyproject.toml*
```
[tool.poetry]
name = "repo"
version = "0.1.0"
description = ""
authors = [""]
readme = ""

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
*project A pyproject.toml*
```
[tool.poetry]
name = "lib-a"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["Soufiane EL ALAMI <soufiane.elalami@outlook.fr>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
*project B pyproject.toml*
```
# repo/B/pyproject.toml
[tool.poetry]
name = "app-B"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["Soufiane EL ALAMI <soufiane.elalami@outlook.fr>"]

[tool.poetry.dependencies]
python = "^3.8"
lib-a = {path = "../A", develop=true}

[tool.poetry-monorepo.deps]
enabled = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
I hope this is useful :)

**Comment by gerbenoostra** [comment]
Hi. Firstly sorry for the late reply, apparently I'm not yet getting email notifications on new issues.

Running `poetry build` from `repo/B` is expected to invoke the plugin, so thanks for reporting.

To diagnose the issue, let's verify a few things first:
1. Could you ensure that the plugin is installed for the poetry you're invoking:
```
poetry self show plugins
```
2. get more debug output:
```
poetry build -vvv
```
The first few lines should be similar to:
```
Loading configuration file ...
Using virtualenv: ...
Replacing path dependencies with named dependencies.
Building project_name (1.2.3)
  - Building sdist
```

**Comment by gerbenoostra** [comment]
Can't reproduce without more diagnostics
